services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2 # Кеширование зависимостей Maven
    depends_on:
      - postgres
    command: ./mvnw spring-boot:run