services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: true
    volumes:
      - .:/app
      - ~/.m2:/root/.m2 # Кеширование зависимостей Maven
    depends_on:
      - postgres
    command: ./mvnw spring-boot:run
    env_file:
      - .env

  postgres:
    ports:
      - "5432:5432"
    env_file:
      - .env