services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: spring_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - todo_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todo_db
      SPRING_DATASOURCE_USERNAME: spring_user
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - todo_network
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  todo_network:
