name: "spring-app"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-todo_db}
      POSTGRES_USER: ${POSTGRES_USER:-spring_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    networks:
      - todo_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-todo_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-spring_user}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    networks:
      - todo_network
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  todo_network:
