services:
  app:
    restart: always
    env_file: !override
      - .env.prod
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]

  postgres:
    restart: always
    env_file: !override
      - .env.prod